expose_php = Off
memory_limit = 256M
upload_max_filesize = 10M
post_max_size = 40M
max_file_uploads = 12
date.timezone = Africa/Abidjan
session.use_strict_mode = 1
session.cookie_httponly = 1
session.gc_maxlifetime = 7200
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
variables_order = "EGPCS"
